In [4]:
import numpy as np

In [ ]:
#1. Write a NumPy program to convert a list of numeric value into a one-dimensional NumPy array. 

In [5]:
a = [12.23, 13.32, 100, 36.32]
b = np.array(a)
print("orignal list:",a)
print("one dimensional numpy array:",b)

orignal list: [12.23, 13.32, 100, 36.32]
one dimensional numpy array: [ 12.23  13.32 100.    36.32]


In [ ]:
#2.Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.   

In [10]:
a = np.arange(2,11)
b = a.reshape(3,3)
b

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [ ]:
#3.Write a NumPy program to create a null vector of size 10 and update sixth value to 11. 

In [16]:
a = np.zeros(10)
print(a)
a[6] = 11
print('updated value:',a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
updated value: [ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


In [ ]:
#4. Write a NumPy program to create an array with values ranging from 12 to 38. 

In [7]:
a = np.arange(12,38)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37])

In [ ]:
#5. Write a NumPy program to reverse an array (first element becomes last). 

In [23]:
a = np.arange(12,38)
print('orignal array:',a)
a = a[::-1]
print('reverse array:',a)

orignal array: [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
reverse array: [37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


In [ ]:
#6. Write a NumPy program to convert an array to a float type.  

In [14]:
a = np.array([1,2,3,4])
print('orignal array:',a)
b = a.astype(float)
print('converted array:',b)

orignal array: [1 2 3 4]
converted array: [1. 2. 3. 4.]


In [ ]:
#7. Write a NumPy program to create a 2d array with 1 on the border and 0 inside. 

In [46]:
a = np.ones((5,5))
print('orignal array:',a)
a[1:-1,1:-1] = 0
print('1 on the border and 0 inside in the array',a)

orignal array: [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
#8. Write a NumPy program to add a border (filled with 0's) around an existing array.  

In [49]:
a = np.ones((5,5))
print('orignal array:',a)
a = np.pad(a, pad_width=1, mode='constant', constant_values=0)
print('1 on the border and 0 inside in the array:',a)

orignal array: [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array: [[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
#9. Write a NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern.  

In [53]:
a = np.zeros((8,8),dtype=int)
a[1::2,::2] = 1
a[::2,1::2] = 1
print('Checkerboard pattern:',a)

Checkerboard pattern: [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
#10. Write a NumPy program to convert a list and tuple into arrays. 

In [4]:
l1 = [1,2,3,4,5,6]
a = np.array(l1)
print('list to array:',a)

tup = ([1,2,3],[4,5,6])
b = np.array(tup)
print('tuple to array:',b)


list to array: [1 2 3 4 5 6]
tuple to array: [[1 2 3]
 [4 5 6]]


In [ ]:
#11. Write a NumPy program to append values to the end of an array.  

In [42]:
a = [10,20,30]
a = np.append(a,[40,50,60,70,80,90])
print('after appending array:',a)

after appending array: [10 20 30 40 50 60 70 80 90]


In [ ]:
#12. Write a NumPy program to create an empty and a full array. 

In [30]:
a = np.empty([3,3])
print(a)
b = np.full([3,3],6)
print(b)

[[6.23042070e-307 4.67296746e-307 1.69121096e-306]
 [6.23047842e-307 2.22526399e-307 6.23053614e-307]
 [7.56592338e-307 9.34588061e-307 3.62651150e-317]]
[[6 6 6]
 [6 6 6]
 [6 6 6]]


In [ ]:
#13.Write a NumPy program to convert the values of Centigrade degrees into Fahrenheit degrees.
#Centigrade values are stored into a NumPy array. 

In [34]:
a = np.array([0, 12, 45.21 ,34, 99.91])
print('Values in Fahrenheit degrees:',a)
b = np.round((5*a/9 - 5*32/9),2)
print('Values in Centigrade degrees:',b)

Values in Fahrenheit degrees: [ 0.   12.   45.21 34.   99.91]
Values in Centigrade degrees: [-17.78 -11.11   7.34   1.11  37.73]


In [ ]:
#14. Write a NumPy program to find the real and imaginary parts of an array of complex numbers.  

In [38]:
a = np.array([1.00000000+0.j+0.70710678+0.70710678j])
print('real part:',a.real)
print('imaginary part:',a.imag)

real part: [1.70710678]
imaginary part: [0.70710678]
